### ISSUE TITLE
Make font friendly to general users

### ISSUE THREAD

**Issue by kiwi0fruit** [StefanPeev/Linguistics-Pro#3]
Maybe it would be better to split font into different font families that correspond to different cyrillic alphabets? So that MS Word Users and CSS users can use it easily?

**Comment by StefanPeev** [comment]
I don't think it's a good idea. The Linguistics Pro is thought to be an LCG font family, strictly covering the Unicode standarts and as a font family which follows the OpenType features. Because the support for the local features in the applications and on the web is much easier nowadays than some years ago (for example there is a full support for local features from v.5.3 in Libre Office), it's better to go in this direction. Probably I'll turn back the international Cyrillic form of glyphs to the default Cyrillic set (uni0410:uni044F) and I'll put the Bulgarian Cyrillic letters as a local ones - supported both by OpenType local features BGR and through the style sets.
As far as MS Word is concerned - I hope that some day Ms Word will support OpenType local features (BGR, SRB, MCD etc.).  Now the local glyphs could be used in Ms Word through use of a style set.

**Comment by kiwi0fruit** [comment]
Is it done via `font-variant` css property
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant ? Or maybe it
can beset right in the `font-family` (or `font` property)?

And how to do it in MS Word (I have no idea...)?

**Comment by StefanPeev** [comment]
In Linguistics Pro by default we have this:
![screenshot-www cyreal org-2018 03 19-17-31-21](https://user-images.githubusercontent.com/12949369/37605664-5ec4ae72-2b9c-11e8-867b-fba69c0812e5.png)

If we use **section lang="ru"**, we receive the next result:

![screenshot-www cyreal org-2018 03 19-17-32-20](https://user-images.githubusercontent.com/12949369/37605665-5f020fc4-2b9c-11e8-9bc2-20767ea2f701.png)

If we use **section lang="sr"**, we receive the next result:

![screenshot-www cyreal org-2018 03 19-17-32-45](https://user-images.githubusercontent.com/12949369/37605667-5f739ea0-2b9c-11e8-93ae-4c0b90fc2464.png)

You could test all these here: [Cyreal](http://www.cyreal.org/Font-Testing-Page/index-cyrillic.php)

So it's quite easy to switch between different Cyrillic languages on the web. On one and the same page but in different div tags or paragraphs you could use different language specifications and thus your web page could be absolutely multilanguage. Try it!

On the other hand as far as I know (I do not use MS Word) from version 10 of MS Word the application supports Style Sets. And in the Linguistics Pro are written the style sets as follow: Stylistic Set 01 is for international (or Russian Cyrillic), Stylistic Set 02 is for Serbian one and Stylistic Set 03 is for Macedonian Cyrillic.

And here is a lesson on [YouTube](https://www.youtube.com/watch?v=Y5cSxpBuHqM) how to use Stylistic Sets in MS Word.

**Comment by kiwi0fruit** [comment]
That didn't helped at all...

After all I found instructions how to switch OpenType variants in CSS:

1. https://helpx.adobe.com/typekit/using/use-open-type-features.html
2. https://helpx.adobe.com/typekit/using/open-type-syntax.html
3. https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings

**Comment by StefanPeev** [comment]
Here is an example on a real web site: you could test it by doing the changes in html at the very begining of the site:

INTERNATIONAL (RUSSIAN) look of the font family:

![centralesans_ru](https://user-images.githubusercontent.com/12949369/37608384-11971e62-2ba3-11e8-87bf-7c27bb378659.jpg)

BULGARIAN look of the font family:

![centralesans_bg](https://user-images.githubusercontent.com/12949369/37608383-1174d226-2ba3-11e8-9d07-ca7882ea7811.jpg)

**Comment by kiwi0fruit** [comment]
Thanks! I only now noticed that you had edited the post.
